export const HOST_115 = {
  NORMAL: '115.com',
  MY: 'my.115.com',
  WEB_API: 'webapi.115.com',
  PRO_API: 'proapi.115.com',
  PASSPORT_API: 'passportapi.115.com',
  QRCODE_API: 'qrcodeapi.115.com',
  CAPTCHA_API: 'captchaapi.115.com',
  AQ: 'aq.115.com',
  ANXIA_API: 'v.anxia.com',
  VOD: '115vod.com',
  APS: 'aps.115.com',
  DL: 'dl.115cdn.net',
  CDN_FILE: 'cdnfhnfile.115cdn.net',
  UPLB: 'uplb.115.com',
} as const

export const URL_115 = {
  NORMAL: `https://${HOST_115.NORMAL}`,
  MY: `https://${HOST_115.MY}`,
  WEB_API: `https://${HOST_115.WEB_API}`,
  PRO_API: `https://${HOST_115.PRO_API}`,
  PASSPORT_API: `https://${HOST_115.PASSPORT_API}`,
  QRCODE_API: `https://${HOST_115.QRCODE_API}`,
  CAPTCHA_API: `https://${HOST_115.CAPTCHA_API}`,
  AQ: `https://${HOST_115.AQ}`,
  ANXIA_API: `https://${HOST_115.ANXIA_API}`,
  VOD: `https://${HOST_115.VOD}`,
  APS: `https://${HOST_115.APS}`,
  DL: `https://${HOST_115.DL}`,
  CDN_FILE: `https://${HOST_115.CDN_FILE}`,
  UPLB: `https://${HOST_115.UPLB}`,
} as const
