import { expect, it } from 'vitest'

it('imports the narrow runtime contract without browser globals', async () => {
  expect(Object.keys(await import('@115master/ui')).sort()).toEqual([
    'ActionMenu',
    'Button',
    'ContextMenu',
    'Dialog',
    'DialogHost',
    'DndMonitor',
    'DndRoot',
    'DndSource',
    'DndTarget',
    'Drawer',
    'Empty',
    'FloatingDock',
    'Header',
    'HeaderEnd',
    'HeaderStart',
    'Image',
    'ModalHost',
    'NavigationStack',
    'OverlayHost',
    'Pagination',
    'Pill',
    'Progress',
    'ResponsiveMenu',
    'SelectionHeader',
    'StatusFeedback',
    'Tooltip',
    'Watermark',
    'createDialogService',
    'scrollbar',
    'useCollectionSelection',
    'useDialog',
  ])
})
